floating:
  - com.apple.mail
  - com.1password.1password
  - com.apple.facetime.FaceTime
  - com.apple.finder
  - ModrinthApp
  - com.overwolf.curseforge
window-margins: true
window-margin-size: 10
smart-window-margins: true
